<?php

$con=mysql_connect("localhost","root","");
mysql_select_db("irs",$con);

if(isset($_POST['submit']))
	{
		$a=$_POST['email'];
		$b=$_POST['name'];
		session_start();
		
		$login=mysql_query("select * from userstore where RegdMail='$a'");
		$row=mysql_fetch_array($login);
		$c = $row['AccType'];
                $reg = $row['Regdno'];
                if($c == 'Student')
                {
                    $forgots = mysql_query("select * from student where RegdMail='$a'");
                    $row1 = mysql_fetch_array($forgots);
                    $d = $row1['Password'];
                    if(mysql_num_rows($login) !=0)

			{
				$_SESSION['RegdMail']=$_POST['email'];
                                //Start of the Mailing
                                $_SESSION['Regdno']=$reg;
                                include 'mail/email.php';
                                             $msg="
                                              Dear   $b,
                                                          <p>Your Password is <b>$d</b> , Signin to your irs account,
                                                          http://localhost/IRS/login.php<br>http://10.1.0.201
                                               <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";
                                           $mail->From = $from1;
                                           $mail->FromName = "Information Repository System"; // Name to indicate where the email came from when the recepient received
                                           $mail->AddAddress($a); // this is for receiver mail id
                                           $mail->WordWrap = 50; // set word wrap
                                           $mail->IsHTML(true); // send as HTML
                                           $mail->Subject = "New Registration "; //used for mail subject
                                           $mail->Body =$msg; //HTML Body
                                           if(!$mail->Send())
                                           {
                                                  echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Some Error Occurred. Check Your Connection!')
                                                    window.location.href='forgotphp'
                                                    </SCRIPT>");
                                           }
                                           else{
                                                echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Password is sent to the respective mail id. Open the provided Email Id.')
                                                    window.location.href='login.php'
                                                    </SCRIPT>");
                                           }
                                         //end of the mailing
 
                              
			}

			else
			{
				 echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Provided Email Id is NOT Registered.')
                                                    window.location.href='forgot.php'
                                                    </SCRIPT>");
			}
                }
                else
                {
                    $forgotf = mysql_query("select * from facstaff where RegdMail='$a'");
                    $row2 = mysql_fetch_array($forgotf);
                    $e = $row2['Password'];
                    if(mysql_num_rows($login) !=0)

			{
				$_SESSION['RegdMail']=$_POST['email'];
                                //Start of the Mailing
                                $_SESSION['Regdno']=$reg;
                                include 'mail/email.php';
                                                $msg="
                                              Dear   $b,
                                                          <p> Your Password is <b>$e </b>, If you want to change your password click on below link,
                                                          http://localhost/IRS/chpas.php<br>http://10.1.0.201
                                               <p style='color:red;'>........this is a autogenerated mail don't reply to it........</p>";
                                           $mail->From = $from1;
                                           $mail->FromName = "Information Repository System"; // Name to indicate where the email came from when the recepient received
                                           $mail->AddAddress($a); // this is for receiver mail id
                                           $mail->WordWrap = 50; // set word wrap
                                           $mail->IsHTML(true); // send as HTML
                                           $mail->Subject = "New Registration "; //used for mail subject
                                           $mail->Body =$msg; //HTML Body
                                           if(!$mail->Send())   
                                           {
                                                  echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Some Error Occurred. Check Your Connection!')
                                                    window.location.href='forgotphp'
                                                    </SCRIPT>");
                                           }
                                           else{
                                               echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Password is sent to the respective mail id. Open the provided Email Id.')
                                                    window.location.href='login.php'
                                                    </SCRIPT>");
                                           }
                                         //end of the mailing
 
                              
			}

			else
			{
				 echo ("<SCRIPT LANGUAGE='JavaScript'>
                                                    window.alert('Provided Email Id is NOT Registered.')
                                                    window.location.href='forgot.php'
                                                    </SCRIPT>");
			}
                }
                        
	}

?>
